### ISSUE TITLE
Compatible with the native Linux TF2 port ?

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [Link2006/TF2CheatDetectLua#1]
Hi there, I was interested into actually do something about that situation and discovered PazerOP project.

However, due to PazerOP ms dependencies, I've found yours which seemed to be a better fit for my use case.

One issue, however, is already at the mounting moment. You see, the UNIX/Linux file setup doesn't use / but instead, \\. _For example, My Team Fortress 2 directory is found at \`_/mnt/Ventilateur/SteamLibrary/steamapps/common/Team Fortress 2/\`. Another thing that might make it quite difficult is that the \\ character is used to type directories with spaces in commands. _For example, If I wanted from the terminal, to go in my Team Fortress 2 directory, I would do a \`cd_ /mnt/Ventilateur/SteamLibrary/steamapps/common/Team\\ Fortress\\ 2/\`.

I've did tried nonetheless to add my Team Fortress 2 folder, as,`/mnt/Ventilateur/SteamLibrary/steamapps/common/Team\ Fortress\ 2/` `\mnt\Ventilateur\SteamLibrary\steamapps\common\Team Fortress 2`without any success.

However, using `/mnt/Ventilateur/SteamLibrary/steamapps/common/Team Fortress 2` did make the game selector part of the script work.

I'm currently checking more if it can be used, but I wanted to know if it was expected to work that way in the first place.

**Comment by PoorPocketsMcNewHold** [comment]
![20200619_083213](https://user-images.githubusercontent.com/13170204/85104303-e2e63e80-b1f7-11ea-9e1f-c3805b30ec7d.png)
I was wondering why in the first place, the script wasn't able to load the console log, but I've then remembered that the example paths directed to the tf folder, and that the two // was meant to read the console.log file. So i've changed them.
![](https://user-images.githubusercontent.com/13170204/85104116-808d3e00-b1f7-11ea-81c5-fd5697a19490.png)
And now, It loads! I don't really know if I should write (Or Bind) the lua_nocheat command in the current running script, game folder or in a separate terminal process, but it loads! Will tell more later when I get in a real bots scenario. For some dumb reason, I've tried with a local bot match.

**Comment by Link2006** [comment]
Yeah on Linux you don't need to use backslashes at all and since it's just a string you also do not need to escapes spaces.

Terminals uses them to say there's a space, but usually that's one of the only places it needs them, scripts usually uses quotes for the location which let's the system know more precisely where to go.

I've tried my best to also respect cases in both file names and scripts so that it doesn't break on Linux either as well as my limited testing, there should not be any weird issues, if anything does break please do make a new issue about it.
